services:
  meeplezone:
    image: mcr.microsoft.com/dotnet/aspnet:10.0
    container_name: MeepleZone
    volumes:
      - /volume1/docker/MeepleZone/App:/app
    working_dir: /app
    command: ["dotnet", "MeepleZone.dll"]
    ports:
      - "8080:8080"
    restart: unless-stopped
