<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>8b470c99-89c0-4851-be60-3b1d1ebfe1bb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.11.0" />
    <ProjectReference Include="..\MeepleZone.Client\MeepleZone.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.12" />
  </ItemGroup>

</Project>
